import { Inter } from "next/font/google";
import PWA from "../components/PWA";
// import "./globals.css";
// import { StudentProvider } from "./context/StudentContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Acadally",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/Acadally_Logo_colleps.svg" type="image/svg+xml" />
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={inter.className}>
        <PWA />
        {children}
      </body>
    </html>
  );
}
